"""
Django settings for system project.

Generated by "django-admin startproject" using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
import sys

from .settings_local import DEBUG  # local config file

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = "/app/docker_django"

SITE_PROTOCOL = "https" if os.environ.get("NGINX_MODE", "non_ssl") == "ssl" else "http"
SITE_DOMAIN = os.environ.get("HOSTNAME")
SITE_URL = f"{SITE_PROTOCOL}://{SITE_DOMAIN}"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Application definition



LANGUAGES = (
    ("uk", "Ukrainian"),
)

LANGUAGE_CODE = "uk"

USE_I18N = True

DATE_FORMAT = "d.m.Y"
_DATE_FORMAT = "%d.%m.%Y"
DATETIME_FORMAT = "d.m.Y H:i"
_DATETIME_FORMAT = "%d.%m.%Y %M:%S"
# DATE_INPUT_FORMATS = [
#     "%d.%m.%Y",
#     "%d %B %Y"
# ]
# DATETIME_INPUT_FORMATS = [
#     "%m.%d.%Y %H:%M",
#     "%m %d %Y %H:%M",
# ]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, "../../locale"),
)


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django.contrib.gis",
    "django.contrib.contenttypes",

    # 3rd-party
    "debug_toolbar",
    "likert_field",
    "rest_framework",
    # "colorful",
    "stronghold",
    "mptt",
    "mailer",
    "nested_admin",
    "compressor",
    # "rest_framework.authtoken",
    # "report_builder",
    # "report_builder",
]
OWN_APPS = [
    "system",
    "users",
    "authorization",
    "client_api",
    "eservice",
    "reports",
    "signature",
    "crypto_info",
    "support",
    "backend",
    "eservice0100043",
    "eservice0100044",
    "nadra",

    "system.choices",
]
INSTALLED_APPS += OWN_APPS

REPORT_BUILDER_GLOBAL_EXPORT = True
ACCOUNT_USERNAME_REQUIRED = False
# Custom user-model
AUTH_USER_MODEL = "users.User"
AUTH_CLIENT_MODEL = "client_api.ClientApi"


# Postgres definations:
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "Because_why_n0tt_Pg",
        "HOST": "db",
        "PORT": "5432",
    },
    "directories": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "sds_testing",
        "USER": "sds_testing",
        "PASSWORD": "zL8wpEBDTD4n",
        "HOST": "91.210.190.70",
        "PORT": "5432",
    },
}

DATABASE_ROUTERS = ["system.db_router.DBRouter", ]

#
# LOGIN_URL = "/uk/accounts/login/"
from django.conf.urls.i18n import i18n_patterns

# LOGIN_REDIRECT_URL = "/uk/accounts/login/"

STRONGHOLD_DEFAULTS = True
STRONGHOLD_PUBLIC_URLS = (
    r'^/client_api/',
)
# STRONGHOLD_PUBLIC_NAMED_URLS = ("admin",)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'system.login_required_middleware.LoginRequiredMiddleware',
    'stronghold.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'admin_ip_restrictor.middleware.AdminIPRestrictorMiddleware',
    # 'system.middlewares.UserGroupPermission',
    # 'system.middlewares.IsAccessGroup',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "system.urls"
COMPRESS_ROOT = os.path.join(BASE_DIR, "static")


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "enadra"
    }
}


if DEBUG:
    COMPRESS_ENABLED = False
else:
    COMPRESS_ENABLED = True

COMPRESS_FILTERS = {
    "css": ["compressor.filters.css_default.CssAbsoluteFilter", "compressor.filters.cssmin.CSSMinFilter"],
    "js": ["compressor.filters.jsmin.JSMinFilter"]
}
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates"), ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
            ],
            # "libraries": {
            #     "common_utils": "system.templatetags.my_admin",
            # },
        },

    },
]

WSGI_APPLICATION = "wsgi.application"
# LOGIN_URL = '/uk/accounts/login/'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


TIME_ZONE = "Europe/Kiev"

# LANGUAGE_CODE = "uk_UA"
DEFAULT_CHARSET = "utf8"

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, "allstatic"))
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)


FIXTURE_DIRS = [os.path.join(BASE_DIR, "development/dumps")]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10
}

PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, "private_files/statement")
PRIVATE_MEDIA_URL = "/private_files/statement"
GET_PRIVATE_MEDIA_URL = "/private_files/get/statement"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

X_FRAME_OPTIONS = "ALLOW-FROM http://www.arcgis.com/"
XS_SHARING_ALLOWED_METHODS = ["POST", "GET", "OPTIONS", "PUT", "DELETE"]

if (DEBUG):
    RESTRICT_ADMIN = False
else:
    RESTRICT_ADMIN = True

ALLOWED_ADMIN_IPS = ["127.0.0.1", "::1"]
ALLOWED_ADMIN_IP_RANGES = ["127.0.0.0/24", "::/1"]
RESTRICTED_APP_NAMES = ["admin"]


# ---------------- #
# django-debug-toolbar
# ---------------- #
DEBUG_TOOLBAR_PATCH_SETTINGS = False
DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
]


CHAT_WS_SERVER_HOST = "localhost"
CHAT_WS_SERVER_PORT = 5002
CHAT_WS_SERVER_PROTOCOL = "ws"


PRIVATBANKID_CLIENT_ID = "bc464eda-423b370b73e7"
PRIVATBANKID_SECRET = "MDczMjhhOi00NmZlLWI4YWY5ZGJiZmQx"


PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAuzyVgNlDHB6uzsCA3GZugQUwTUJhKJanZI8qrqA3rx3kKLUx
dKZgcK3CurqK0hiVPAibP9yLLTXwXco8l7k63QoGAABDMlJw2Nl9aD8RHpCQg2j5
aGBdIOSlc2LRwIDnvwDiQWnXXe4bf9x9pc+B5HegDVtXKTtlfR/kNX8Co3z86uoC
1tN/fAUJRG4hbF4bDJ06Yb/0Cup1brGeICsKWJj0ekIq/BnNy4yTh6qPQOdpgzII
SngajvOEZeH290PkarI4rr3jnpl+
uBX6KnUCgYEA9FNkbk83azqa6nEKR0LxuM4Ep7fGjIuxOqWREqTDAS7LdtgQdRHF
waZ4pdS04FMh/2mL0p6g9dZ72iyaphuy0MWHU+3yBACT8L44N/Ztjr2n75zVNiSx
ACk8Pu42Ld2tF67lL9EKv1dKO2aIgfBEeZEfNcCVcZiiaOY0rjwiYx8CgYEAxC7f
1XAHqMFy8YNOH3IQc7NqCxrRbRYuSI7fxCkXYmigsTbCB/VXe23Bx/om6m2lW9ku
xaMRVInexsVoappOCTbdWY/6Vf+7IyWAhTjmrq/n1HUMdz9g9w3f5DOQPtImf+kV
WEHIxP/HJ+46tncGfmqKHy/qpa5aa/xUlwIkYnsCgYB//tQFSfCxdyFDIncNABAc
Dam4p3kXlfMB00zd5HzYOMiUePqeKfJc0bYwwe8D+ek8ofGDJGEUiQmXMXjO/oG+
B00u9d+soxTdsPlIsAuTFN5Ok+3KkIw9llyeZzLw8knEt3YPh8bGmJcl6UAoOlPV
D+a2xS5FNX4X0EnW4V/uZwKBgB2ImPW+uchz5uPoynf9afChD9PAI8ryTeFqcNFN
BlIwQhCrl6YvDw5rxYJfbEBaZUxgc6QZGmDJqJnv2fpCZIEKm2QCQsNzji6KVMC5
gjDGFnZrcIb7KZPHqO7nvE1Ywab75dS1go31m3utZ3VUkcuyKjzrr71ldANRp0Jc
djHFAoGBAMviacJqkYtznXwf0bKnaB1tJhbYBH1rzrECzKJvLA+2x82Qn7dTo9Dq
gizpUUUhKHZCL+3ktTEOqegL506r0cGyWfnSKwTcx3pzwFm6E9DftWRYFtRdtjS7
MPgFYHBMrZIbz95O5NVyjlvwIXUycubqJT+ldMDUA9hSgLemK9Au
-----END RSA PRIVATE KEY-----"""

PRIVATBANKID_AUTH_DOMAIN = "https://bankid.org.ua"
PRIVATBANKID_GETDATA_DOMAIN = "https://bankid.org.ua"

PRIVATE_KEY_SIGN = ""
PUBLIC_KEY_SIGN = ""

try:
    from .base_celery import *
except ImportError:
    sys.stderr.write("Unable to read system.settings.base_celery.py!\n")

try:
    from .settings_local import *
except ImportError:
    sys.stderr.write("Unable to read system.settings.settings_local.py!\n")