# Generated by Django 2.0.9 on 2019-03-11 16:08

import datetime
from django.db import migrations, models
import django_extensions.db.fields.json
import eservice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Населений пункт')),
            ],
            options={
                'db_table': 'geo_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=128, unique=True, verbose_name='Індекс реєстрації послуги')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Створено')),
                ('title', models.CharField(max_length=512, validators=[eservice.models.validate_capitalized], verbose_name='Короткий опис')),
                ('created_by_ip', models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP адреса автора картки')),
                ('deadline', models.DateField(null=True, verbose_name='Кінечний строк')),
                ('close_at', models.DateTimeField(null=True, verbose_name='Послуга завершенна')),
                ('version', models.IntegerField(default='1', verbose_name='Версія послуги')),
                ('period_extended', models.DateTimeField(blank=True, null=True, verbose_name='Дата продовження послуги')),
                ('resolutioner_viewed', models.BooleanField(default=False, verbose_name='Переглянуто резолюцілнером')),
                ('edit_comment', models.CharField(max_length=1024, null=True, verbose_name='Коментар відправившого на доопрацювання')),
                ('is_deleted', models.CharField(default=False, max_length=10, null=True, verbose_name='Видалено?')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'db_table': 'eservice',
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='EServiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to=eservice.models.user_directory_path, validators=[eservice.models.file_extension])),
                ('filename', models.CharField(default='Custom name', max_length=128)),
                ('mime', models.CharField(default='image/jpeg', max_length=150, verbose_name='Тип файлу')),
                ('size', models.IntegerField(null=True, verbose_name='Розмір файлу')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файли',
                'db_table': 'eservice_file',
            },
        ),
        migrations.CreateModel(
            name='EServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Лог подій по послуги',
                'verbose_name_plural': 'Логі подій по послуги',
                'db_table': 'eservice_log',
            },
        ),
        migrations.CreateModel(
            name='EServiceMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_index', models.CharField(max_length=10, verbose_name='Індекс категорії')),
                ('title', models.CharField(max_length=1024, verbose_name='Назва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('is_category', models.BooleanField(default=False, verbose_name='Категорія?')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('attr', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True, verbose_name='Додаткова інформація')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Мета-інформація',
                'verbose_name_plural': 'Мета-інформація',
                'db_table': 'eservice_meta',
            },
        ),
        migrations.CreateModel(
            name='EServiceOnApproving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by_ip', models.CharField(default='127.0.0.1', max_length=15)),
                ('done', models.IntegerField(default=0)),
                ('done_at', models.DateTimeField(null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('submitted', models.BooleanField(default=0)),
                ('comment', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'eservice_on_approving',
            },
        ),
        migrations.CreateModel(
            name='EServiceStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('quality', models.FloatField(blank=True, default=None, null=True)),
                ('easy_ordering', models.FloatField(blank=True, default=None, null=True)),
                ('term_service', models.FloatField(blank=True, default=None, null=True)),
                ('average_value', models.FloatField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Оцінюваня надання послуги',
                'verbose_name_plural': 'Оцінюваня надання послуги',
                'db_table': 'eservice_star',
            },
        ),
        migrations.CreateModel(
            name='EServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Чернетка', max_length=160)),
                ('slug', models.CharField(default='draft', max_length=60)),
                ('color', models.CharField(default='text-default', max_length=60)),
            ],
            options={
                'verbose_name': 'Статус послуги',
                'verbose_name_plural': 'Статуси послуги',
                'db_table': 'eservice_status',
            },
        ),
        migrations.CreateModel(
            name='EServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(default='Вхідна кореспонденція', max_length=128)),
                ('controller', models.CharField(default='dev', max_length=128)),
                ('model', models.CharField(default='EService', max_length=128)),
            ],
            options={
                'verbose_name': 'Тип послуги',
                'verbose_name_plural': 'Типи послуги',
                'db_table': 'eservice_type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eservicestatus',
            unique_together={('title', 'slug')},
        ),
    ]
