# Generated by Django 2.0.9 on 2019-03-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0002_auto_20190311_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eservice',
            options={'select_on_save': True, 'verbose_name': 'Послуги', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterField(
            model_name='eservice',
            name='close_at',
            field=models.DateTimeField(null=True, verbose_name='Послугу завершенно'),
        ),
        migrations.AlterField(
            model_name='eservicefile',
            name='eservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eservice.EService', verbose_name='Послугу'),
        ),
    ]
