# Generated by Django 2.0.9 on 2019-03-11 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=64, verbose_name='По батькові')),
                ('password_api', models.CharField(max_length=128, verbose_name='Пароль')),
                ('login_api', models.CharField(max_length=128, verbose_name='Логін')),
                ('ip_or_domain', models.CharField(max_length=64, verbose_name='Особистий телефон')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'Клієнти',
                'verbose_name_plural': 'Клієнта',
            },
        ),
        migrations.CreateModel(
            name='ClientApiEService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_api.ClientApi', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Клієнти_Послуги',
                'verbose_name_plural': 'Клієнти_Послуги',
            },
        ),
        migrations.CreateModel(
            name='ClientApiEServiceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64, verbose_name='Поле')),
                ('client_api_eservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_api.ClientApiEService', verbose_name='Клієнт')),
            ],
        ),
    ]
