# Generated by Django 2.0.9 on 2019-03-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eservice', '0001_initial'),
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapieservice',
            name='eservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eservice.EServiceType', verbose_name='Послуга'),
        ),
        migrations.AlterUniqueTogether(
            name='clientapieservice',
            unique_together={('client', 'eservice')},
        ),
    ]
