# Generated by Django 2.0.9 on 2019-03-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_auto_20190311_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientapi',
            options={'verbose_name': 'Клієнти', 'verbose_name_plural': 'Клієнти'},
        ),
    ]
