# Generated by Django 2.0.9 on 2019-03-19 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190311_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувачі', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterField(
            model_name='deptemp',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2101, 5, 8, 13, 14, 41, 745790), verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='deptmanager',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2101, 5, 8, 13, 14, 41, 747838), verbose_name='to'),
        ),
    ]
