# Generated by Django 2.0.9 on 2019-03-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EService0100044',
            fields=[
                ('eservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eservice.EService')),
                ('comment2', models.TextField(null=True, verbose_name='Докладний опис2')),
                ('region2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Область2')),
                ('city2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Місто2')),
                ('payment2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_meta2', to='eservice.EServiceMeta')),
                ('type_license2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_license_meta2', to='eservice.EServiceType')),
            ],
            options={
                'verbose_name': 'eservice0100044',
                'verbose_name_plural': 'eservice0100044',
                'db_table': 'eservice0100044',
            },
            bases=('eservice.eservice',),
        ),
    ]
