# Generated by Django 2.0.9 on 2019-03-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eservice0100044', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eservice0100044',
            name='type_license2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_license_meta2', to='eservice.EServiceMeta'),
        ),
    ]
