# Generated by Django 2.0.9 on 2019-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('cl_id', models.CharField(max_length=64, null=True, unique=True)),
                ('cl_id_text', models.CharField(default='', max_length=512)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
        migrations.CreateModel(
            name='UserTemporaryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_user_temporary_code',
            },
        ),
    ]
