# Generated by Django 2.1.3 on 2018-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('date_registered', models.DateField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usersquestion',
            name='used_id',
        ),
        migrations.AddField(
            model_name='question',
            name='cost',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersquestion',
            name='answer',
            field=models.CharField(default='answer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersquestion',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
