# Generated by Django 2.0.9 on 2019-03-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20190311_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Діалог', 'verbose_name_plural': 'Діалоги'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created'], 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
    ]
