# Generated by Django 2.0.9 on 2019-03-20 11:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eservice', '0003_auto_20190319_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='NadraModel',
            fields=[
                ('eservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eservice.EService')),
                ('pib', models.CharField(blank=True, max_length=200, null=True, verbose_name='ПІБ')),
                ('info_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Інформація про особу підписанта Угоди про умови користування надрами  (посада та ПІБ)')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('inn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ідентифікаційний номер')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Місцезнаходження')),
                ('info_document', models.CharField(blank=True, max_length=200, null=True, verbose_name='Інформація про документ')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Телефон')),
                ('organ', models.CharField(blank=True, max_length=200, null=True, verbose_name='Відповідальний орган')),
                ('comment', models.TextField(null=True, verbose_name='Докладний опис')),
                ('signature', models.TextField(null=True, verbose_name='Підпис')),
            ],
            options={
                'verbose_name': 'nadra',
                'verbose_name_plural': 'nadra',
                'db_table': 'nadra',
            },
            bases=('eservice.eservice',),
        ),
        migrations.AddField(
            model_name='areas',
            name='nadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadra.NadraModel'),
        ),
    ]
